[[redirects]]
  from = "/dogs/*"
  to = "/dogs/[slug].html"
  status = 200
  force = true
[build]
  command = "npm run build"
  publish = "out"
[build.environment]
  NODE_VERSION = "18.20.4"
[[plugins]]
  package = "@netlify/plugin-nextjs"